// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as update$0 from "../internal/update/models.js";

/**
 * ImportResult reports an import.
 */
export class ImportResult {
    "added": number;
    "failed": string[];

    /** Creates a new ImportResult instance. */
    constructor($$source: Partial<ImportResult> = {}) {
        if (!("added" in $$source)) {
            this["added"] = 0;
        }
        if (!("failed" in $$source)) {
            this["failed"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ImportResult {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("failed" in $$parsedSource) {
            $$parsedSource["failed"] = $$createField1_0($$parsedSource["failed"]);
        }
        return new ImportResult($$parsedSource as Partial<ImportResult>);
    }
}

/**
 * State describes the backend to the frontend.
 */
export class State {
    "version": string;

    /**
     * Error is set when the service failed to start, for example because a
     * headless "godl service" already holds the loopback port.
     */
    "error"?: string;
    "defaultDirectory": string;
    "autostart": boolean;

    /**
     * Update is set when a newer release is available.
     */
    "update"?: update$0.Release | null;

    /** Creates a new State instance. */
    constructor($$source: Partial<State> = {}) {
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("defaultDirectory" in $$source)) {
            this["defaultDirectory"] = "";
        }
        if (!("autostart" in $$source)) {
            this["autostart"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new State instance from a string or object.
     */
    static createFrom($$source: any = {}): State {
        const $$createField4_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("update" in $$parsedSource) {
            $$parsedSource["update"] = $$createField4_0($$parsedSource["update"]);
        }
        return new State($$parsedSource as Partial<State>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = update$0.Release.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
