// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * State describes the backend to the frontend.
 */
export class State {
    "version": string;

    /**
     * Error is set when the service failed to start, for example because a
     * headless "godl service" already holds the loopback port.
     */
    "error"?: string;
    "defaultDirectory": string;
    "autostart": boolean;

    /** Creates a new State instance. */
    constructor($$source: Partial<State> = {}) {
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("defaultDirectory" in $$source)) {
            this["defaultDirectory"] = "";
        }
        if (!("autostart" in $$source)) {
            this["autostart"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new State instance from a string or object.
     */
    static createFrom($$source: any = {}): State {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new State($$parsedSource as Partial<State>);
    }
}
