// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * optionalNotifier starts the notification service without letting its
 * failure stop the app: Wails aborts when any service fails to start.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as notifications$0 from "../../../wailsapp/wails/v3/pkg/services/notifications/models.js";

export function CheckNotificationAuthorization(): $CancellablePromise<boolean> {
    return $Call.ByID(3430453798);
}

export function RegisterNotificationCategory(category: notifications$0.NotificationCategory): $CancellablePromise<void> {
    return $Call.ByID(3113433736, category);
}

export function RemoveAllDeliveredNotifications(): $CancellablePromise<void> {
    return $Call.ByID(1273668381);
}

export function RemoveAllPendingNotifications(): $CancellablePromise<void> {
    return $Call.ByID(69861076);
}

export function RemoveDeliveredNotification(identifier: string): $CancellablePromise<void> {
    return $Call.ByID(600293661, identifier);
}

export function RemoveNotification(identifier: string): $CancellablePromise<void> {
    return $Call.ByID(1659726177, identifier);
}

export function RemoveNotificationCategory(categoryID: string): $CancellablePromise<void> {
    return $Call.ByID(3281749725, categoryID);
}

export function RemovePendingNotification(identifier: string): $CancellablePromise<void> {
    return $Call.ByID(2536647302, identifier);
}

/**
 * Public methods that delegate to the implementation.
 */
export function RequestNotificationAuthorization(): $CancellablePromise<boolean> {
    return $Call.ByID(1280213061);
}

export function SendNotification(options: notifications$0.NotificationOptions): $CancellablePromise<void> {
    return $Call.ByID(230182339, options);
}

export function SendNotificationWithActions(options: notifications$0.NotificationOptions): $CancellablePromise<void> {
    return $Call.ByID(1226345358, options);
}

/**
 * UpdateNotification updates an in-flight notification by ID. On macOS this
 * is auto-deduplicated by UNUserNotificationCenter; on Linux it uses the
 * D-Bus replaces_id parameter. On Windows it currently redelivers as a new
 * notification (true replace requires upstream wintoast support for tag/group).
 */
export function UpdateNotification(options: notifications$0.NotificationOptions): $CancellablePromise<void> {
    return $Call.ByID(1654689296, options);
}
