// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Config is the user-facing proxy configuration.
 */
export class Config {
    "mode"?: Mode;

    /**
     * manual only: http://, https://, or socks5:// with optional user:pass@
     */
    "url"?: string;

    /** Creates a new Config instance. */
    constructor($$source: Partial<Config> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     */
    static createFrom($$source: any = {}): Config {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Config($$parsedSource as Partial<Config>);
    }
}

/**
 * Mode selects where proxy settings come from.
 */
export enum Mode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * default when empty
     */
    ModeSystem = "system",
    ModeNone = "none",
    ModeManual = "manual",
};
