// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as download$0 from "../../../../zichuanxu/nimget/internal/download/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as update$0 from "../../../../zichuanxu/nimget/internal/update/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "clipboard": string;
            "download": download$0.Event;
            "queue-done": string;
            "update": update$0.Release;
        }
    }
}
