// Command packaging renders the package-manager manifests for a release from
// its checksum files: the Homebrew formula (CLI) and cask (desktop app) for
// zichuanxu/homebrew-tap, Scoop manifests for zichuanxu/scoop-bucket, and a
// winget manifest set for microsoft/winget-pkgs (DESIGN.md section 10).
//
//	go run ./tools/packaging -version 1.0.0 -checksums dist/checksums.txt,dist/desktop-checksums.txt -out out
package main

import (
	"bufio"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

const repo = "https://github.com/zichuanxu/godl"

func main() {
	version := flag.String("version", "", "release version without the v, for example 1.0.0")
	sums := flag.String("checksums", "", "comma-separated checksum files (sha256  name)")
	out := flag.String("out", "packaging-out", "output directory")
	flag.Parse()
	if err := run(*version, strings.Split(*sums, ","), *out); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run(version string, sumFiles []string, out string) error {
	if version == "" || strings.HasPrefix(version, "v") {
		return fmt.Errorf("-version must be like 1.0.0, got %q", version)
	}
	sha := map[string]string{}
	for _, path := range sumFiles {
		if err := readSums(path, sha); err != nil {
			return err
		}
	}
	data := map[string]any{"Version": version, "Repo": repo}
	assets := map[string]string{
		"DarwinArm64": "godl_%s_darwin_arm64.tar.gz", "DarwinAmd64": "godl_%s_darwin_amd64.tar.gz",
		"LinuxArm64": "godl_%s_linux_arm64.tar.gz", "LinuxAmd64": "godl_%s_linux_amd64.tar.gz",
		"WindowsZip": "godl_%s_windows_amd64.zip", "Dmg": "godl-desktop_%s_macos_universal.dmg",
		"DesktopZip": "godl-desktop_%s_windows_amd64.zip", "Setup": "godl-desktop_%s_windows_amd64_setup.exe",
	}
	for key, pattern := range assets {
		name := fmt.Sprintf(pattern, version)
		sum, ok := sha[name]
		if !ok {
			return fmt.Errorf("no checksum for %s", name)
		}
		data[key] = map[string]string{"Name": name, "SHA": sum, "URL": fmt.Sprintf("%s/releases/download/v%s/%s", repo, version, name)}
	}
	wingetDir := filepath.Join("winget", "manifests", "z", "zichuanxu", "godl", version)
	files := map[string]string{
		filepath.Join("homebrew-tap", "Formula", "godl.rb"):          formula,
		filepath.Join("homebrew-tap", "Casks", "godl-desktop.rb"):    cask,
		filepath.Join("scoop-bucket", "bucket", "godl.json"):         scoopCLI,
		filepath.Join("scoop-bucket", "bucket", "godl-desktop.json"): scoopDesktop,
		filepath.Join(wingetDir, "zichuanxu.godl.yaml"):              wingetVersion,
		filepath.Join(wingetDir, "zichuanxu.godl.installer.yaml"):    wingetInstaller,
		filepath.Join(wingetDir, "zichuanxu.godl.locale.en-US.yaml"): wingetLocale,
	}
	funcs := template.FuncMap{"upper": strings.ToUpper}
	for path, text := range files {
		tmpl := template.Must(template.New(path).Funcs(funcs).Parse(text))
		full := filepath.Join(out, path)
		if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
			return err
		}
		f, err := os.Create(full)
		if err != nil {
			return err
		}
		err = tmpl.Execute(f, data)
		if cerr := f.Close(); err == nil {
			err = cerr
		}
		if err != nil {
			return fmt.Errorf("%s: %w", path, err)
		}
	}
	return nil
}

func readSums(path string, into map[string]string) error {
	f, err := os.Open(path)
	if err != nil {
		return err
	}
	defer f.Close()
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		fields := strings.Fields(scanner.Text())
		if len(fields) == 2 && len(fields[0]) == 64 {
			into[strings.TrimPrefix(fields[1], "*")] = strings.ToLower(fields[0])
		}
	}
	return scanner.Err()
}

const formula = `# Generated by tools/packaging for v{{.Version}}.
class Godl < Formula
  desc "Fast, cross-platform download manager: command-line client and service"
  homepage "{{.Repo}}"
  version "{{.Version}}"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "{{.DarwinArm64.URL}}"
      sha256 "{{.DarwinArm64.SHA}}"
    end
    on_intel do
      url "{{.DarwinAmd64.URL}}"
      sha256 "{{.DarwinAmd64.SHA}}"
    end
  end

  on_linux do
    on_arm do
      url "{{.LinuxArm64.URL}}"
      sha256 "{{.LinuxArm64.SHA}}"
    end
    on_intel do
      url "{{.LinuxAmd64.URL}}"
      sha256 "{{.LinuxAmd64.SHA}}"
    end
  end

  def install
    bin.install "godl"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/godl version")
  end
end
`

const cask = `# Generated by tools/packaging for v{{.Version}}.
cask "godl-desktop" do
  version "{{.Version}}"
  sha256 "{{.Dmg.SHA}}"

  url "{{.Repo}}/releases/download/v#{version}/godl-desktop_#{version}_macos_universal.dmg"
  name "godl"
  desc "Fast download manager with a menu bar app"
  homepage "{{.Repo}}"

  depends_on macos: ">= :monterey"

  app "godl.app"

  zap trash: "~/Library/Application Support/godl"

  caveats <<~EOS
    godl is free and unsigned: it is not notarized by Apple. On first launch,
    if macOS says it cannot verify the developer, open System Settings >
    Privacy & Security and choose "Open Anyway", or run:
      xattr -dr com.apple.quarantine /Applications/godl.app
  EOS
end
`

const scoopCLI = `{
    "version": "{{.Version}}",
    "description": "Fast, cross-platform download manager: command-line client and service.",
    "homepage": "{{.Repo}}",
    "license": "Apache-2.0",
    "architecture": {
        "64bit": {
            "url": "{{.WindowsZip.URL}}",
            "hash": "{{.WindowsZip.SHA}}"
        }
    },
    "bin": "godl.exe",
    "checkver": "github",
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "{{.Repo}}/releases/download/v$version/godl_$version_windows_amd64.zip"
            }
        }
    }
}
`

const scoopDesktop = `{
    "version": "{{.Version}}",
    "description": "Fast download manager with a tray app (desktop edition of godl).",
    "homepage": "{{.Repo}}",
    "license": "Apache-2.0",
    "notes": "godl is unsigned; if SmartScreen warns, choose More info > Run anyway.",
    "architecture": {
        "64bit": {
            "url": "{{.DesktopZip.URL}}",
            "hash": "{{.DesktopZip.SHA}}"
        }
    },
    "shortcuts": [["godl.exe", "godl"]],
    "checkver": "github",
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "{{.Repo}}/releases/download/v$version/godl-desktop_$version_windows_amd64.zip"
            }
        }
    }
}
`

const wingetVersion = `# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.6.0.schema.json
PackageIdentifier: zichuanxu.godl
PackageVersion: {{.Version}}
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.6.0
`

const wingetInstaller = `# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
PackageIdentifier: zichuanxu.godl
PackageVersion: {{.Version}}
InstallerType: nullsoft
Scope: user
InstallModes:
  - interactive
  - silent
UpgradeBehavior: install
Installers:
  - Architecture: x64
    InstallerUrl: {{.Setup.URL}}
    InstallerSha256: {{upper .Setup.SHA}}
ManifestType: installer
ManifestVersion: 1.6.0
`

const wingetLocale = `# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json
PackageIdentifier: zichuanxu.godl
PackageVersion: {{.Version}}
PackageLocale: en-US
Publisher: zichuanxu
PublisherUrl: https://github.com/zichuanxu
PackageName: godl
PackageUrl: {{.Repo}}
License: Apache-2.0
LicenseUrl: {{.Repo}}/blob/main/LICENSE
ShortDescription: A fast, cross-platform download manager.
Description: godl downloads over many connections with byte-level resume, schedules and limits downloads, imports browser requests as cURL commands, and saves HLS streams.
Tags:
  - download-manager
  - downloader
  - hls
ReleaseNotesUrl: {{.Repo}}/releases/tag/v{{.Version}}
ManifestType: defaultLocale
ManifestVersion: 1.6.0
`
