// Command packaging renders the package-manager manifests for a release from
// its checksum files: the Homebrew formula (CLI) and cask (desktop app) for
// zichuanxu/homebrew-tap and Scoop manifests for zichuanxu/scoop-bucket
// (DESIGN.md section 10).
//
//	go run ./tools/packaging -version 1.0.0 -checksums dist/checksums.txt,dist/desktop-checksums.txt -out out
package main

import (
	"bufio"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

const repo = "https://github.com/zichuanxu/nimget"

func main() {
	version := flag.String("version", "", "release version without the v, for example 1.0.0")
	sums := flag.String("checksums", "", "comma-separated checksum files (sha256  name)")
	out := flag.String("out", "packaging-out", "output directory")
	flag.Parse()
	if err := run(*version, strings.Split(*sums, ","), *out); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run(version string, sumFiles []string, out string) error {
	if version == "" || strings.HasPrefix(version, "v") {
		return fmt.Errorf("-version must be like 1.0.0, got %q", version)
	}
	sha := map[string]string{}
	for _, path := range sumFiles {
		if err := readSums(path, sha); err != nil {
			return err
		}
	}
	data := map[string]any{"Version": version, "Repo": repo}
	assets := map[string]string{
		"DarwinArm64": "nimget_%s_darwin_arm64.tar.gz", "DarwinAmd64": "nimget_%s_darwin_amd64.tar.gz",
		"LinuxArm64": "nimget_%s_linux_arm64.tar.gz", "LinuxAmd64": "nimget_%s_linux_amd64.tar.gz",
		"WindowsZip": "nimget_%s_windows_amd64.zip", "Dmg": "nimget-desktop_%s_macos_universal.dmg",
		"DesktopZip": "nimget-desktop_%s_windows_amd64.zip",
	}
	for key, pattern := range assets {
		name := fmt.Sprintf(pattern, version)
		sum, ok := sha[name]
		if !ok {
			return fmt.Errorf("no checksum for %s", name)
		}
		data[key] = map[string]string{"Name": name, "SHA": sum, "URL": fmt.Sprintf("%s/releases/download/v%s/%s", repo, version, name)}
	}
	files := map[string]string{
		filepath.Join("homebrew-tap", "Formula", "nimget.rb"):          formula,
		filepath.Join("homebrew-tap", "Casks", "nimget-desktop.rb"):    cask,
		filepath.Join("scoop-bucket", "bucket", "nimget.json"):         scoopCLI,
		filepath.Join("scoop-bucket", "bucket", "nimget-desktop.json"): scoopDesktop,
	}
	for path, text := range files {
		tmpl := template.Must(template.New(path).Parse(text))
		full := filepath.Join(out, path)
		if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
			return err
		}
		f, err := os.Create(full)
		if err != nil {
			return err
		}
		err = tmpl.Execute(f, data)
		if cerr := f.Close(); err == nil {
			err = cerr
		}
		if err != nil {
			return fmt.Errorf("%s: %w", path, err)
		}
	}
	return nil
}

func readSums(path string, into map[string]string) error {
	f, err := os.Open(path)
	if err != nil {
		return err
	}
	defer f.Close()
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		fields := strings.Fields(scanner.Text())
		if len(fields) == 2 && len(fields[0]) == 64 {
			into[strings.TrimPrefix(fields[1], "*")] = strings.ToLower(fields[0])
		}
	}
	return scanner.Err()
}

const formula = `# Generated by tools/packaging for v{{.Version}}.
class Nimget < Formula
  desc "Fast, cross-platform download manager: command-line client and service"
  homepage "{{.Repo}}"
  version "{{.Version}}"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "{{.DarwinArm64.URL}}"
      sha256 "{{.DarwinArm64.SHA}}"
    end
    on_intel do
      url "{{.DarwinAmd64.URL}}"
      sha256 "{{.DarwinAmd64.SHA}}"
    end
  end

  on_linux do
    on_arm do
      url "{{.LinuxArm64.URL}}"
      sha256 "{{.LinuxArm64.SHA}}"
    end
    on_intel do
      url "{{.LinuxAmd64.URL}}"
      sha256 "{{.LinuxAmd64.SHA}}"
    end
  end

  def install
    bin.install "nimget"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/nimget version")
  end
end
`

const cask = `# Generated by tools/packaging for v{{.Version}}.
cask "nimget-desktop" do
  version "{{.Version}}"
  sha256 "{{.Dmg.SHA}}"

  url "{{.Repo}}/releases/download/v#{version}/nimget-desktop_#{version}_macos_universal.dmg"
  name "NimGet"
  desc "Lightweight, open-source download manager built in Go"
  homepage "{{.Repo}}"

  depends_on macos: ">= :monterey"

  app "NimGet.app"

  zap trash: "~/Library/Application Support/nimget"

  caveats <<~EOS
    NimGet is free and unsigned: it is not notarized by Apple. On first launch,
    if macOS says it cannot verify the developer, open System Settings >
    Privacy & Security and choose "Open Anyway", or run:
      xattr -dr com.apple.quarantine /Applications/NimGet.app
  EOS
end
`

const scoopCLI = `{
    "version": "{{.Version}}",
    "description": "Fast, cross-platform download manager: command-line client and service.",
    "homepage": "{{.Repo}}",
    "license": "Apache-2.0",
    "architecture": {
        "64bit": {
            "url": "{{.WindowsZip.URL}}",
            "hash": "{{.WindowsZip.SHA}}"
        }
    },
    "bin": "nimget.exe",
    "checkver": "github",
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "{{.Repo}}/releases/download/v$version/nimget_$version_windows_amd64.zip"
            }
        }
    }
}
`

const scoopDesktop = `{
    "version": "{{.Version}}",
    "description": "NimGet: a fast desktop download manager built in Go.",
    "homepage": "{{.Repo}}",
    "license": "Apache-2.0",
    "notes": "NimGet is unsigned; if SmartScreen warns, choose More info > Run anyway.",
    "architecture": {
        "64bit": {
            "url": "{{.DesktopZip.URL}}",
            "hash": "{{.DesktopZip.SHA}}"
        }
    },
    "shortcuts": [["nimget.exe", "NimGet"]],
    "checkver": "github",
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "{{.Repo}}/releases/download/v$version/nimget-desktop_$version_windows_amd64.zip"
            }
        }
    }
}
`
