// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as netproxy$0 from "../netproxy/models.js";

/**
 * Desktop holds preferences only the desktop app reads.
 */
export class Desktop {
    "clipboardMonitor": boolean;
    "notifications": boolean;

    /**
     * AskDirectory asks for a folder on every add instead of using the
     * category folders.
     */
    "askDirectory": boolean;

    /**
     * OpenWhenDone opens each file with its default app when it completes.
     */
    "openWhenDone": boolean;

    /**
     * FFmpeg is the ffmpeg executable for converting streams to MP4; empty
     * means ffmpeg on PATH.
     */
    "ffmpeg"?: string;

    /**
     * CheckUpdates polls GitHub Releases once a week for a newer version.
     */
    "checkUpdates": boolean;

    /**
     * Language is the interface language: "en", "zh-CN", or empty for the
     * system's.
     */
    "language"?: string;

    /** Creates a new Desktop instance. */
    constructor($$source: Partial<Desktop> = {}) {
        if (!("clipboardMonitor" in $$source)) {
            this["clipboardMonitor"] = false;
        }
        if (!("notifications" in $$source)) {
            this["notifications"] = false;
        }
        if (!("askDirectory" in $$source)) {
            this["askDirectory"] = false;
        }
        if (!("openWhenDone" in $$source)) {
            this["openWhenDone"] = false;
        }
        if (!("checkUpdates" in $$source)) {
            this["checkUpdates"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Desktop instance from a string or object.
     */
    static createFrom($$source: any = {}): Desktop {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Desktop($$parsedSource as Partial<Desktop>);
    }
}

/**
 * Schedule runs the queue only between Start and Stop ("HH:MM" local time,
 * wrapping past midnight) and applies time-of-day speed limits. Empty Start and
 * Stop run the queue all day.
 */
export class Schedule {
    "start"?: string;
    "stop"?: string;
    "speedRules"?: SpeedRule[];

    /** Creates a new Schedule instance. */
    constructor($$source: Partial<Schedule> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Schedule instance from a string or object.
     */
    static createFrom($$source: any = {}): Schedule {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("speedRules" in $$parsedSource) {
            $$parsedSource["speedRules"] = $$createField2_0($$parsedSource["speedRules"]);
        }
        return new Schedule($$parsedSource as Partial<Schedule>);
    }
}

export class Settings {
    /**
     * MaxConcurrent is the number of downloads running at once.
     */
    "maxConcurrent": number;

    /**
     * Connections is the default per download, 1 to 32.
     */
    "connections": number;

    /**
     * HostConnections caps connections to one host across all downloads.
     */
    "hostConnections": number;

    /**
     * SpeedLimit caps all downloads together in bytes per second; 0 is none.
     */
    "speedLimit": number;
    "schedule": Schedule;
    "proxy": netproxy$0.Config;
    "sites": Site[];

    /**
     * ExtraRoots are directories picked in the GUI; downloads may be written
     * under them as well as under the service's download roots.
     */
    "extraRoots": string[];
    "desktop": Desktop;

    /** Creates a new Settings instance. */
    constructor($$source: Partial<Settings> = {}) {
        if (!("maxConcurrent" in $$source)) {
            this["maxConcurrent"] = 0;
        }
        if (!("connections" in $$source)) {
            this["connections"] = 0;
        }
        if (!("hostConnections" in $$source)) {
            this["hostConnections"] = 0;
        }
        if (!("speedLimit" in $$source)) {
            this["speedLimit"] = 0;
        }
        if (!("schedule" in $$source)) {
            this["schedule"] = (new Schedule());
        }
        if (!("proxy" in $$source)) {
            this["proxy"] = (new netproxy$0.Config());
        }
        if (!("sites" in $$source)) {
            this["sites"] = [];
        }
        if (!("extraRoots" in $$source)) {
            this["extraRoots"] = [];
        }
        if (!("desktop" in $$source)) {
            this["desktop"] = (new Desktop());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     */
    static createFrom($$source: any = {}): Settings {
        const $$createField4_0 = $$createType2;
        const $$createField5_0 = $$createType3;
        const $$createField6_0 = $$createType5;
        const $$createField7_0 = $$createType6;
        const $$createField8_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("schedule" in $$parsedSource) {
            $$parsedSource["schedule"] = $$createField4_0($$parsedSource["schedule"]);
        }
        if ("proxy" in $$parsedSource) {
            $$parsedSource["proxy"] = $$createField5_0($$parsedSource["proxy"]);
        }
        if ("sites" in $$parsedSource) {
            $$parsedSource["sites"] = $$createField6_0($$parsedSource["sites"]);
        }
        if ("extraRoots" in $$parsedSource) {
            $$parsedSource["extraRoots"] = $$createField7_0($$parsedSource["extraRoots"]);
        }
        if ("desktop" in $$parsedSource) {
            $$parsedSource["desktop"] = $$createField8_0($$parsedSource["desktop"]);
        }
        return new Settings($$parsedSource as Partial<Settings>);
    }
}

/**
 * Site overrides settings for a host and its subdomains. Zero fields inherit.
 */
export class Site {
    "host": string;
    "connections"?: number;
    "hostConnections"?: number;
    "headers"?: { [_ in string]?: string };
    "username"?: string;
    "password"?: string;

    /** Creates a new Site instance. */
    constructor($$source: Partial<Site> = {}) {
        if (!("host" in $$source)) {
            this["host"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Site instance from a string or object.
     */
    static createFrom($$source: any = {}): Site {
        const $$createField3_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("headers" in $$parsedSource) {
            $$parsedSource["headers"] = $$createField3_0($$parsedSource["headers"]);
        }
        return new Site($$parsedSource as Partial<Site>);
    }
}

/**
 * SpeedRule replaces the global speed limit between From and To.
 */
export class SpeedRule {
    "from": string;
    "to": string;
    "limit": number;

    /** Creates a new SpeedRule instance. */
    constructor($$source: Partial<SpeedRule> = {}) {
        if (!("from" in $$source)) {
            this["from"] = "";
        }
        if (!("to" in $$source)) {
            this["to"] = "";
        }
        if (!("limit" in $$source)) {
            this["limit"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SpeedRule instance from a string or object.
     */
    static createFrom($$source: any = {}): SpeedRule {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SpeedRule($$parsedSource as Partial<SpeedRule>);
    }
}

// Private type creation functions
const $$createType0 = SpeedRule.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = Schedule.createFrom;
const $$createType3 = netproxy$0.Config.createFrom;
const $$createType4 = Site.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $Create.Array($Create.Any);
const $$createType7 = Desktop.createFrom;
const $$createType8 = $Create.Map($Create.Any, $Create.Any);
