// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Event {
    "sequence"?: number;
    "type": EventType;
    "item": Item;

    /** Creates a new Event instance. */
    constructor($$source: Partial<Event> = {}) {
        if (!("type" in $$source)) {
            this["type"] = EventType.$zero;
        }
        if (!("item" in $$source)) {
            this["item"] = (new Item());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Event instance from a string or object.
     */
    static createFrom($$source: any = {}): Event {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("item" in $$parsedSource) {
            $$parsedSource["item"] = $$createField2_0($$parsedSource["item"]);
        }
        return new Event($$parsedSource as Partial<Event>);
    }
}

export enum EventType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    EventUpdated = "updated",
    EventProgress = "progress",
    EventDeleted = "deleted",
};

export class Item {
    "id": string;
    "url": string;
    "destination": string;
    "status": Status;
    "completed": number;
    "total": number;
    "error"?: string;
    "priority": number;

    /**
     * Connections overrides the site and default connection count when set.
     */
    "connections"?: number;

    /**
     * SpeedLimit caps this download in bytes per second; 0 is none.
     */
    "speedLimit"?: number;
    "checksum"?: string;
    "createdAt": string;
    "updatedAt": string;

    /** Creates a new Item instance. */
    constructor($$source: Partial<Item> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("destination" in $$source)) {
            this["destination"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = Status.$zero;
        }
        if (!("completed" in $$source)) {
            this["completed"] = 0;
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("priority" in $$source)) {
            this["priority"] = 0;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Item instance from a string or object.
     */
    static createFrom($$source: any = {}): Item {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Item($$parsedSource as Partial<Item>);
    }
}

/**
 * Patch changes a download's options; nil fields are left alone. A new speed
 * limit applies immediately, new connections from the next start.
 */
export class Patch {
    "priority"?: number | null;
    "connections"?: number | null;
    "speedLimit"?: number | null;

    /**
     * Headers replace the request headers, for example after the session
     * cookie expired; they apply from the next start.
     */
    "headers"?: { [_ in string]?: string } | null;

    /** Creates a new Patch instance. */
    constructor($$source: Partial<Patch> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Patch instance from a string or object.
     */
    static createFrom($$source: any = {}): Patch {
        const $$createField3_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("headers" in $$parsedSource) {
            $$parsedSource["headers"] = $$createField3_0($$parsedSource["headers"]);
        }
        return new Patch($$parsedSource as Partial<Patch>);
    }
}

/**
 * Request adds a download. Without a Destination the file name comes from the
 * server, placed in Directory or in the root's category folder.
 */
export class Request {
    "url": string;
    "destination"?: string;
    "directory"?: string;
    "priority"?: number;
    "connections"?: number;
    "speedLimit"?: number;
    "checksum"?: string;
    "headers"?: { [_ in string]?: string };

    /** Creates a new Request instance. */
    constructor($$source: Partial<Request> = {}) {
        if (!("url" in $$source)) {
            this["url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Request instance from a string or object.
     */
    static createFrom($$source: any = {}): Request {
        const $$createField7_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("headers" in $$parsedSource) {
            $$parsedSource["headers"] = $$createField7_0($$parsedSource["headers"]);
        }
        return new Request($$parsedSource as Partial<Request>);
    }
}

export enum Status {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StatusQueued = "queued",
    StatusRunning = "running",
    StatusPaused = "paused",
    StatusCompleted = "completed",
    StatusFailed = "failed",
};

// Private type creation functions
const $$createType0 = Item.createFrom;
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
const $$createType2 = $Create.Nullable($$createType1);
